<?php

include_once 'header.php';
include_once 'database.php';
include_once 'methods.php';
include_once "check_access_permissions.php";

mustHaveAllOfTheseRoles( array( 'AWS_ADMIN' ) );

function createEmailEntry( $speaker, $date )
{
    // Now insert a entry into email database.
    $msg = getEmailTemplateById( 'aws_confirmed_notify_speaker' );
    // Replace text in the template.
    $msg = str_replace( '%SPEAKER%', loginToText( $speaker, $msg ); 
    $msg = str_replace( '%DATE%', humanReadableDate( $date, $msg ); 

    // Store this to database.
    $data = array( "recipients" => getLoginEmail( $speaker )
        , "subject" => "We have fixed date of your next AWS"
        , "msg" => $msg 
        , "when_to_send" => dbDateTime( strtotime( '+1 day' ) 
    );
    insertIntoTable( 'emails', 'recipients,subject,msg,when_to_send', $data ); 
}

if( $_POST['response'] == "Reschedule" )
{
    $cwd = getcwd( );
    echo printInfo( "Rescheduling ...." );
    $scriptPath = $cwd . '/schedule.sh';
    echo("<pre>Executing $scriptPath with timeout 30 secs</pre>");
    $command = "timeout 30 bash $scriptPath";
    exec( $command );
    goToPage( 'admin_aws_manages_upcoming_aws.php', 1);
    exit;
}
else if( $_POST[ 'response' ] == 'Accept' || $_POST[ 'response' ] == 'Assign' )
{
    $speaker = $_POST[ 'speaker' ];
    $date = $_POST[ 'date' ];
    echo printInfo( "Assigning $speaker to $date" );
    // Accept the schedule generated by minion.
    $res = acceptScheduleOfAWS( $speaker, $date );
    if( $res )
    {
        echo printInfo( "Successfully assigned" );
        createEmailEntry( $_POST[ 'speaker' ], $_POST[ 'date' ] );
        goToPage( "admin_aws_manages_upcoming_aws.php", 1 );
        exit;
    }
}
else if( $_POST[ 'response' ] == 'Clear' )
{
    $res = clearUpcomingAWS( $_POST[ 'speaker'], $_POST[ 'date' ] );
    if( $res )
    {
        echo printInfo( "Successfully cleared upcoming AWS" );
        goToPage( "admin_aws_manages_upcoming_aws.php", 2 );
        exit;
    }
}
else
{
    echo printWarning( "To Do " . $_POST[ 'response' ] );
}

echo goBackToPageLink( "admin_aws_manages_upcoming_aws.php", "Go back" );

?>

