<?php 

include_once( "header.php" );
include_once( "methods.php" );
include_once( "tohtml.php" );

?>

<script type="text/javascript">
function toggleMe(source) {
    var checkboxes = document.getElementsByName( 'events[]' );
    for( var index = 0; index < checkboxes.length; ++index )
        checkboxes[index].checked = source.checked;
}
</script>


<?php
if( $_POST['response'] == "Review" )
{
    // Approve after constructing all the events from the patterns.
    $requests = getRequestByGroupIdAndStatus( $_POST['gid'], 'PENDING' );

    echo "<h3> Following list of events are generated by this request </h3>";
    // First insert this request into event calendar.
    echo '<form method="post" action="admin_request_submit.php">';
    echo "<table>";
    echo "<tr> 
        <td><input name=\"request[]\" type=\"checkbox\" 
            onclick=\"toggleMe(this)\" />Check all</td>
            <!-- Here we create the button to submit requests -->
            <td> 
                <button name=\"response\" value=\"APPROVE\">Approve selected </button>
                <button name=\"response\" value=\"REJECT\">reject selected</button>
            </td>
        </tr>
        ";
    $childrenId = 0;
    foreach( $requests as $r )
    {
        $gid = $r['gid'];
        $rid = $r['rid'];
        // use this id to get back the gid and rid in next form. 
        $id = $gid . '.' . $rid;
        echo "<tr>";
        echo "<td><input type=\"checkbox\" name=\"events[]\" value=\"$id\"></td>";
        echo "<td>" . requestToHTMLTable( $r ) . "</td>";
        echo '<td>TODO: check venue</td>';
        echo '</tr>';
    }
    echo '</td>';
    echo "</tr> </table>";
    echo "</form>";
}

//goToPage( "admin.php", 5 );

?>
