<?php

include_once 'header.php';
include_once 'database.php';
include_once 'methods.php';
include_once "check_access_permissions.php";

mustHaveAllOfTheseRoles( array( 'AWS_ADMIN' ) );

if( $_POST['response'] == "Reschedule" )
{
    $cwd = getcwd( );
    $resfilePath = tempnam( "/tmp", "minion" );

    echo printInfo( "Rescheduling ...." );
    $scriptPath = $cwd . '/schedule_aws.py';
    echo("<pre>Executing $scriptPath with timeout 30 secs</pre>");
    $command = "timeout 30 $scriptPath";
    exec( $command );
    goToPage( 'admin_aws_manages_upcoming_aws.php', 0 );
    exit;
}
else if( $_POST[ 'response' ] == 'Accept' )
{
    echo printInfo( "Accepting following request" );

    // Accept the schedule generated by minion.
    $res = acceptScheduleOfAWS( $_POST[ 'speaker' ], $_POST[ 'date' ] );
    if( $res )
    {
        echo printInfo( "Successfully assigned" );
        goToPage( "admin_aws_manages_upcoming_aws.php", 1 );
        exit;
    }
}
else if( $_POST[ 'response' ] == 'Clear' )
{
    $res = clearUpcomingAWS( $_POST[ 'speaker'], $_POST[ 'date' ] );
    if( $res )
    {
        echo printInfo( "Successfully cleared upcoming AWS" );
        goToPage( "admin_aws_manages_upcoming_aws.php", 2 );
        exit;
    }
}
else if( $_POST['response'] == 'Assign' )
{
    $speaker = $_POST[ 'speaker' ];
    $date = $_POST[ 'date' ];
    $res = acceptScheduleOfAWS( $speaker, $date );
    if( $res )
    {
        echo printInfo( "Successfully assigned." );
        goToPage( "admin_aws_manages_upcoming_aws.php", 1 );
        exit;
    }
}
else
{
    echo printWarning( "To Do " . $_POST[ 'response' ] );
}

echo goBackToPageLink( "admin_aws_manages_upcoming_aws.php", "Go back" );

?>

