<?php 

include_once( "header.php" );
include_once( "methods.php" );
include_once( "tohtml.php" );
include_once( 'database.php' );

?>

<script type="text/javascript">
function toggleMe(source) {
    var checkboxes = document.getElementsByName( 'events[]' );
    for( var index = 0; index < checkboxes.length; ++index )
        checkboxes[index].checked = source.checked;
}
</script>


<?php
if( $_POST['response'] == "Review" )
{
    // Approve after constructing all the events from the patterns.
    $requests = getRequestByGroupIdAndStatus( $_POST['gid'], 'PENDING' );

    echo "<h3> Following list of events are generated by this request </h3>";
    echo "<p class=\"info\">While approving, I'll ask you if you want to put 
        this event on public calendar. </p>";

    echo "<p class=\"info\">Before approving, you may change some fields of 
        a request by clicking on 'Edit' button. </p>";

    // First insert this request into event calendar.
    echo '<form method="post" action="admin_request_submit.php">';
    echo "<table>";
    echo "<tr> 
        <td><input name=\"request[]\" type=\"checkbox\" 
            onclick=\"toggleMe(this)\" />Check all</td>
            <!-- Here we create the button to submit requests -->
            <td> <font size=\"1\" color=\"blue\">Put on public calendar</font>
                <br>
                <input name=\"isPublic\" value=\"YES\" type=\"radio\" />Yes
                <input name=\"isPublic\" value=\"NO\" type=\"radio\" checked />No
                <button name=\"response\" value=\"APPROVE\">Approve selected </button>
                <button name=\"response\" value=\"REJECT\">reject selected</button>
            </td>
        </tr>
        ";
    $childrenId = 0;
    foreach( $requests as $r )
    {
        $gid = $r['gid'];
        $rid = $r['rid'];
        // use this id to get back the gid and rid in next form. 
        $id = $gid . '.' . $rid;
        echo "<tr>";
        echo "<td><input type=\"checkbox\" name=\"events[]\" value=\"$id\"></td>";
        $tobefiltered = Array( 'modified_by', 'rid', 'timestamp' );
        echo "<td>" . arrayToTableHTML( $r, 'request', $tobefiltered ) . "</td>";

        //echo "<td> <font color=\"blue\" size=\"1\">
                //Available on public calendar?</font><br>
            //<input type=\"radio\" name=\"isPublic\" value=\"NO\" checked /> No
            //<input type=\"radio\" name=\"isPublic\" value=\"YES\" /> Yes
            //</td>";
        echo '<td> <button name="response" value="edit">Edit</button></td>';
        echo '</tr>';
    }
    echo '</td>';
    echo "</tr> </table>";
    echo "</form>";
}

?>
