<?php 

include_once( "header.php" );
include_once( "methods.php" );
include_once( "tohtml.php" );
include_once( 'database.php' );
include_once 'check_access_permissions.php';

mustHaveAllOfTheseRoles( array( 'BOOKMYVENUE_ADMIN' ) );

echo userHTML( );

?>

<script type="text/javascript">
function toggleMe(source) {
    var checkboxes = document.getElementsByName( 'events[]' );
    for( var index = 0; index < checkboxes.length; ++index )
        checkboxes[index].checked = source.checked;
}
</script>


<?php
if( ! array_key_exists( 'response', $_POST ) )
{
    echo printInfo( "Nothing to do here anymore" );
    goToPage( './bookmyvenue_admin.php', 0 );
    exit;
}

if( $_POST['response'] == "Review" )
{
    echo '<div>';
    // Approve after constructing all the events from the patterns.
    $requests = getRequestByGroupIdAndStatus( $_POST['gid'], 'PENDING' );
    $gid = $requests[0]['gid'];
    $total = count( $requests );

    echo "<h3> Following events are generated by this request </h3>";

    // First insert this request into event calendar.
    echo '<div style="font-size:small">';
    echo '<form method="post" action="bookmyvenue_admin_request_review_submit.php">';
    echo '<table class="show_events">';
    $childrenId = 0;

    foreach( $requests as $r )
    {
        $rid = $r['rid'];
        // use this id to get back the gid and rid in next form. 
        $id = $gid . '.' . $rid;
        echo "<tr>";
        echo "<td><input type=\"checkbox\" name=\"events[]\" value=\"$id\" checked></td>";
        $tobefiltered = Array( 'status', 'modified_by', 'rid', 'timestamp', 'external_id' );
        echo "<td>" . arrayToTableHTML( $r, 'request', '', $tobefiltered ) . "</td>";

    }

    $yesChecked = '';
    $noChecked = '';
    if( $requests[0][ 'is_public_event' ] == 'YES' )
        $yesChecked = 'checked';
    else
        $noChecked = 'checked';

    echo '</td>';
    echo "</tr> </table>";

    echo "<input name=\"request[]\" type=\"checkbox\" checked
        onclick=\"toggleMe(this)\" />Select all</td>
        ";

    echo printWarning( 
                "Be sure to select some entries before taking any action." 
            );
    echo "<br />";
    echo '</div>';

    echo '<table style="border:1px;position:"relative";"> ';

    echo "<tr> 
            <!-- Here we create the button to submit requests -->
            <td> Suitable for public google-calendar 
                <input name=\"isPublic\" value=\"YES\" type=\"radio\" $yesChecked />Yes
                <input name=\"isPublic\" value=\"NO\" type=\"radio\" $noChecked />No
                </td>
            </tr>
            <tr>
                <td> </td>
                <td>
                    <button name=\"response\" value=\"APPROVE\" 
                        title=\"Approve selected\">" . $symbApprove . "</button>
                </td>
            </tr>
            <tr> 
                <td>
                Reason for rejection <br />
                <textarea rows=\"4\" cols=\"50\" name=\"reason\" 
                    placeholder=\"Mandatorty while rejecting a request \"
                    ></textarea>
                </td>
                <td>
                    <button name=\"response\" value=\"REJECT\"
                        title=\"Reject selected\">" . $symbReject . "</button>
                </td>
            </tr>

            <input type=\"hidden\" name=\"gid\" value=\"$gid\" /> 
        </table>
        ";
    echo "</form>";
    echo '</div>';
}

echo goBackToPageLink( "bookmyvenue_admin.php", "Go back" );

?>
