<?php 

include_once( "header.php" );
include_once( "methods.php" );
include_once( "tohtml.php" );
include_once( 'database.php' );

echo userHTML( );

?>

<script type="text/javascript">
function toggleMe(source) {
    var checkboxes = document.getElementsByName( 'events[]' );
    for( var index = 0; index < checkboxes.length; ++index )
        checkboxes[index].checked = source.checked;
}
</script>


<?php
if( $_POST['response'] == "Review" )
{
    // Approve after constructing all the events from the patterns.
    $requests = getRequestByGroupIdAndStatus( $_POST['gid'], 'PENDING' );
    $gid = $requests[0]['gid'];
    $total = count( $requests );

    echo "<h3> Following events are generated by this request </h3>";

    echo "<p class=\"info\">Before approving, you may change some fields of 
        a request by clicking on 'Edit' button. </p>";

    // First insert this request into event calendar.
    echo '<form method="post" action="bookmyvenue_admin_request_review_submit.php">';
    echo "<table>";
    echo "<tr> 
            <td>
            <input name=\"request[]\" type=\"checkbox\" 
            onclick=\"toggleMe(this)\" />Select all</td>
            <!-- Here we create the button to submit requests -->
            <td> <font size=\"1\" color=\"blue\">Put on public calendar</font>
                <br>
                <input name=\"isPublic\" value=\"YES\" type=\"radio\" />Yes
                <input name=\"isPublic\" value=\"NO\" type=\"radio\" checked />No
                <button name=\"response\" value=\"APPROVE\">Approve selected </button>
                <button name=\"response\" value=\"REJECT\">Reject selected</button>
                <input type=\"hidden\" name=\"gid\" value=\"$gid\" />
            </td>
        </tr>
        </table>
        ";
    echo '<table class="show_events">';
    $childrenId = 0;
    foreach( $requests as $r )
    {
        $rid = $r['rid'];
        // use this id to get back the gid and rid in next form. 
        $id = $gid . '.' . $rid;
        echo "<tr>";
        echo "<td><input type=\"checkbox\" name=\"events[]\" value=\"$id\"></td>";
        $tobefiltered = Array( 'modified_by', 'rid', 'timestamp' );
        echo "<td>" . arrayToTableHTML( $r, 'request', '', $tobefiltered ) . "</td>";
    }
    echo '</td>';
    echo "</tr> </table>";
    echo "</form>";
}

echo goBackToPageLink( "bookmyvenue_admin.php", "Go back" );

?>
