<?php 

include_once( "header.php" );
include_once( "methods.php" );
include_once( "tohtml.php" );
include_once( 'database.php' );

echo userHTML( );

?>

<script type="text/javascript">
function toggleMe(source) {
    var checkboxes = document.getElementsByName( 'events[]' );
    for( var index = 0; index < checkboxes.length; ++index )
        checkboxes[index].checked = source.checked;
}
</script>


<?php
if( $_POST['response'] == "Review" )
{
    echo '<div>';
    // Approve after constructing all the events from the patterns.
    $requests = getRequestByGroupIdAndStatus( $_POST['gid'], 'PENDING' );
    $gid = $requests[0]['gid'];
    $total = count( $requests );

    echo "<h3> Following events are generated by this request </h3>";

    // First insert this request into event calendar.
    echo '<form method="post" action="bookmyvenue_admin_request_review_submit.php">';
    echo '<table class="show_events">';
    $childrenId = 0;
    foreach( $requests as $r )
    {
        $rid = $r['rid'];
        // use this id to get back the gid and rid in next form. 
        $id = $gid . '.' . $rid;
        echo "<tr>";
        echo "<td><input type=\"checkbox\" name=\"events[]\" value=\"$id\"></td>";
        $tobefiltered = Array( 'modified_by', 'rid', 'timestamp' );
        echo "<td>" . arrayToTableHTML( $r, 'request', '', $tobefiltered ) . "</td>";
    }
    echo '</td>';
    echo "</tr> </table>";

    echo "<input name=\"request[]\" type=\"checkbox\" 
        onclick=\"toggleMe(this)\" />Select all</td>
        ";

    echo "<br /> <br />";
    echo '<table 
        style="border:1px;position:"relative";">
        ';
    echo "<tr> 
            <!-- Here we create the button to submit requests -->
            <td> Suitable for public google-calendar </td>
            <td>
                <input name=\"isPublic\" value=\"YES\" type=\"radio\" />Yes
                <input name=\"isPublic\" value=\"NO\" type=\"radio\" checked />No
                </td>
            </tr>
            <tr>
                <td> </td>
                <td>
                    <button name=\"response\" value=\"APPROVE\">Approve selected </button>
                </td>
            </tr>
            <tr> 
                <td>
                Reason for rejection <br />
                <textarea rows=\"4\" cols=\"50\" name=\"reason\" 
                    placeholder=\"Mandatorty while rejecting a request \"
                    ></textarea>
                </td>
                <td>
                    <button name=\"response\" value=\"REJECT\">Reject selected</button>
                </td>
            </tr>

            <input type=\"hidden\" name=\"gid\" value=\"$gid\" /> 
        </table>
        ";
    echo "</form>";
    echo '</div>';
}

echo goBackToPageLink( "bookmyvenue_admin.php", "Go back" );

?>
