<?php

include_once 'database.php';

// Directory to store the mdsum of sent emails.
$maildir = getDataDir( ) . '/_mails';
if( ! file_exists( $maildir ) )
    mkdir( $maildir, 0777, true );

function mailFooter( )
{
    return "
        <p>==========================================================</p>
        This email is automatically generated by NCBS Hippo (https://ncbs.res.in/hippo). 
        If you are not an intended recipient of this email, please write to 
        hippo@lists.ncbs.res.in or acadoffice@ncbs.res.in .
        <p>==========================================================</p>
        ";
}


function sendEmail($msg, $sub, $to) 
{

    $conf = getConf( );
    if( ! array_key_exists( 'send_emails', $conf['global' ] ) )
    {
        echo printInfo( "Email service has not been configured." );
        error_log( "Mail service is not configured" );
        return;
    }

    if( $_SESSION[ 'conf' ]['global']['send_emails' ] == false )
        return;

    $timestamp = date( 'r', strtotime( 'now' ) );

    $msg .= mailFooter( );
    $msgfile = tempnam( '/tmp', 'hippo_temp_msg' );

    file_put_contents( $msgfile, $msg );
    $to = implode( ' -t ', explode( ',', trim( $to ) ) );

    $cmd= __DIR__ . "/sendmail.py -t $to \"-s $sub\" \"-i $msgfile\"";
    $out = exec( $cmd, $output, $ret );
    unlink( $msgfile );
    return true;
}

function sendPlainTextEmail($msg, $sub, $to, $cclist='', $attachment = null) 
{

    global $maildir;
    $conf = getConf( );

    // generate md5 of email. And store it in archive.
    $archivefile = $maildir . '/' . md5($subject . $mail) . '.email';
    if( file_exists( $archivefile ) )
    {
        echo printInfo( "This email has already been sent. Doing nothing" );
        return;
    }


    if( ! array_key_exists( 'send_emails', $conf['global' ] ) )
    {
        echo printInfo( "Email service has not been configured." );
        error_log( "Mail service is not configured" );
        return;
    }


    if( $conf['global']['send_emails' ] == false )
    {
        echo "<br>Sending emails has been disabled in this installation";
        return;
    }

    $timestamp = date( 'r', strtotime( 'now' ) );

    $msg .= mailFooter( );

    $textMail = html2Markdown( $msg );

    $msgfile = tempnam( '/tmp', 'hippo_msg' );
    file_put_contents( $msgfile, $textMail );

    $to =  implode( ' -t ', explode( ',', trim( $to ) ) );

    // Use \" whenever possible. ' don't escape especial characters in bash.
    $cmd= __DIR__ . "/sendmail.py -t $to -s \"$sub\" -i \"$msgfile\" ";

    if( $cclist )
    {
        $cclist =  implode( ' -c ', explode( ',', trim( $cclist ) ) );
        $cmd .= "-c $cclist";
    }

    if( $attachment )
    {
        foreach( explode( ',', $attachment ) as $f )
            $cmd .= " -a \"$f\" ";
    }

    echo "<pre> $cmd </pre>";
    $out = exec( $cmd, $output, $ret );

    echo printInfo( "Saving the mail in archive" . $archivefile );
    file_put_contents( $archivefile, "SENT" );
    unlink( $msgfile );

    return true;
}


// $res = sendEmail( "testing"
//     , "Your request has been created"
//     , "dilawars@ncbs.res.in" 
//     );

?>
